### ISSUE TITLE
Capability to read single header array

### ISSUE THREAD

**Issue by charlie0389** [GEMPACKsoftware/HARPY#25]
- Implement bug fix (needs HarFileInfoObj in har_file_io module).
- HarFileObj should inherit a 'last modified' property from the file.
1. User scans HarFile to see what headers arrays in it (name, size, type etc.).
2. Harpy scans entire file.
3. User now modifies har file, either:
    (a) through another har file obj
    (b) through external program
4. Problem: User uses old header array information to read.
5. Solution:
   (a) Perform a read immediately before executing a write.
   (b) Check against last modified, to ensure file has not changed (if date has changed, scanned information is invalid -> raise exception (with option to suppress exceptions/raise a warning)).

**Comment by floschiffmann** [comment]
HarFileObj has now HarFileInfoObj as well as headerArrs. Info obj is fully created when HarFileObj is instanciated. Info object has is_valid which checks existence and mod time. if not valid HarFileObj is recreated with the updated file and a warning is issued.
headerArrs are only read (arrayData) if header is requested. This is checked by testing if header is in InfoObj but not in headerArr dict
